// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: expense.sql

package expense

import (
	"context"
	"database/sql"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expense (description, amount, created_date, user_id, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, description, amount, created_date, user_id, category
`

type CreateExpenseParams struct {
	Description string          `json:"description"`
	Amount      string          `json:"amount"`
	CreatedDate sql.NullTime    `json:"created_date"`
	UserID      int32           `json:"user_id"`
	Category    ExpenseCategory `json:"category"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.Description,
		arg.Amount,
		arg.CreatedDate,
		arg.UserID,
		arg.Category,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
		&i.UserID,
		&i.Category,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expense WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, description, amount, created_date, user_id, category FROM expense WHERE id = $1 AND user_id = $2
`

type GetExpenseByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
		&i.UserID,
		&i.Category,
	)
	return i, err
}

const getExpensesByCategory = `-- name: GetExpensesByCategory :many
SELECT id, description, amount, created_date, user_id, category FROM expense WHERE user_id = $1 AND category = $2
`

type GetExpensesByCategoryParams struct {
	UserID   int32           `json:"user_id"`
	Category ExpenseCategory `json:"category"`
}

func (q *Queries) GetExpensesByCategory(ctx context.Context, arg GetExpensesByCategoryParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CreatedDate,
			&i.UserID,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByUserID = `-- name: GetExpensesByUserID :many
SELECT id, description, amount, created_date, user_id, category FROM expense WHERE user_id = $1
`

func (q *Queries) GetExpensesByUserID(ctx context.Context, userID int32) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CreatedDate,
			&i.UserID,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expense
SET description = $2, amount = $3, created_date = $4, category = $5
WHERE id = $1 AND user_id = $6
RETURNING id, description, amount, created_date, user_id, category
`

type UpdateExpenseParams struct {
	ID          int32           `json:"id"`
	Description string          `json:"description"`
	Amount      string          `json:"amount"`
	CreatedDate sql.NullTime    `json:"created_date"`
	Category    ExpenseCategory `json:"category"`
	UserID      int32           `json:"user_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.CreatedDate,
		arg.Category,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
		&i.UserID,
		&i.Category,
	)
	return i, err
}
