// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package expense

import (
	"database/sql"
)

type Expense struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	Description string       `json:"description"`
	Amount      string       `json:"amount"`
	CreatedDate sql.NullTime `json:"created_date"`
}
