// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package expense

import (
	"context"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	DeleteExpense(ctx context.Context, id int32) error
	GetExpenseByID(ctx context.Context, id int32) (Expense, error)
	ListExpensesByUserID(ctx context.Context, userID int32) ([]Expense, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
}

var _ Querier = (*Queries)(nil)
