// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package expense

import (
	"context"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, description, amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, description, amount, created_date
`

type CreateExpenseParams struct {
	UserID      int32  `json:"user_id"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense, arg.UserID, arg.Description, arg.Amount)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, user_id, description, amount, created_date
FROM expenses
WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id int32) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
	)
	return i, err
}

const listExpensesByUserID = `-- name: ListExpensesByUserID :many
SELECT id, user_id, description, amount, created_date
FROM expenses
WHERE user_id = $1
ORDER BY created_date DESC
`

func (q *Queries) ListExpensesByUserID(ctx context.Context, userID int32) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.CreatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description = $2, amount = $3
WHERE id = $1
RETURNING id, user_id, description, amount, created_date
`

type UpdateExpenseParams struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense, arg.ID, arg.Description, arg.Amount)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.CreatedDate,
	)
	return i, err
}
